<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-KRM7DIQ6" name="RetryMultiple" tests="10" failures="2" timestamp="15 May 2022 10:06:36 GMT" time="0.039" errors="0">
  <testcase name="test1" time="0.008" classname="RunRetryAnalyzer.Test1">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.001" classname="RunRetryAnalyzer.Test1">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.001" classname="RunRetryAnalyzer.Test1">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.001" classname="RunRetryAnalyzer.Test1">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.0" classname="RunRetryAnalyzer.Test1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at RunRetryAnalyzer.Test1.test1(Test1.java:9)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.0" classname="RunRetryAnalyzer.Test1">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.001" classname="RunRetryAnalyzer.Test1">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.001" classname="RunRetryAnalyzer.Test1">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.0" classname="RunRetryAnalyzer.Test1">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.0" classname="RunRetryAnalyzer.Test1">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at RunRetryAnalyzer.Test1.test2(Test1.java:14)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- RetryMultiple -->
